/** 국내 아티스트 한글↔영문 별칭 데이터 (같은 배열 = 같은 아티스트) */

export const ARTIST_ALIAS_GROUPS: readonly (readonly string[])[] = [
  // —— 걸그룹
  ["fromis_9", "fromis9", "프로미스나인", "프로미스 나인"],
  ["aespa", "æspa", "에스파", "애스파"],
  ["BLACKPINK", "블랙핑크"],
  ["NewJeans", "뉴진스"],
  ["IVE", "아이브"],
  ["LE SSERAFIM", "LESSERAFIM", "르세라핌"],
  ["(G)I-DLE", "GIDLE", "아이들", "여자아이들"],
  ["TWICE", "트와이스"],
  ["Red Velvet", "레드벨벳"],
  ["ITZY", "있지"],
  ["NMIXX", "엔믹스"],
  ["ILLIT", "아일릿"],
  ["BABYMONSTER", "베이비몬스터"],
  ["TWS", "투어스"],
  ["MAMAMOO", "마마무"],
  ["Apink", "에이핑크"],
  ["Oh My Girl", "오마이걸"],
  ["WJSN", "우주소녀"],
  ["LOONA", "이달의 소녀"],
  ["Kep1er", "케플러"],
  ["STAYC", "스테이씨"],
  ["KISS OF LIFE", "키스오브라이프", "킾라"],
  ["tripleS", "트리플에스"],
  ["ARTMS", "아르테미스"],
  ["QWER", "큐더블유이알"],
  ["Girls' Generation", "소녀시대", "SNSD"],
  ["2NE1", "투애니원"],
  ["Wonder Girls", "원더걸스"],
  ["f(x)", "에프엑스"],

  // —— 보이그룹
  ["BTS", "방탄소년단", "방탄"],
  ["ZEROBASEONE", "ZB1", "제로베이스원"],
  ["RIIZE", "라이즈"],
  ["BOYNEXTDOOR", "보이넥스트도어"],
  ["ENHYPEN", "엔하이픈"],
  ["TOMORROW X TOGETHER", "TXT", "투모로우바이투게더"],
  ["Stray Kids", "스트레이키즈", "스키즈"],
  ["SEVENTEEN", "세븐틴"],
  ["ATEEZ", "에이티즈"],
  ["THE BOYZ", "더보이즈"],
  ["NCT", "엔시티"],
  ["NCT DREAM", "엔시티 드림", "엔시티드림"],
  ["NCT 127", "엔시티 127", "엔시티127"],
  ["NCT WISH", "엔시티 위시", "엔시티위시"],
  ["WayV", "웨이션브이"],
  ["EXO", "엑소"],
  ["SHINee", "샤이니"],
  ["BIGBANG", "빅뱅"],
  ["Super Junior", "슈퍼주니어"],
  ["TREASURE", "트레저"],
  ["iKON", "아이콘"],
  ["WINNER", "위너"],
  ["GOT7", "갓세븐"],
  ["MONSTA X", "몬스타엑스"],
  ["ASTRO", "아스트로"],
  ["SF9", "에스에프나인"],
  ["AB6IX", "에이비식스"],
  ["CIX", "씨아이엑스"],
  ["ONEUS", "원어스"],
  ["ONEWE", "원위"],
  ["PENTAGON", "펜타곤"],
  ["VICTON", "빅톤"],
  ["VERIVERY", "베리베리"],
  ["EPEX", "이펙스"],
  ["TEMPEST", "템페스트"],
  ["EVNNE", "이븐"],
  ["xikers", "싸이커스"],
  ["AMPERS&ONE", "앰퍼샌드원"],
  ["PLAVE", "플레이브"],
  ["xdinary Heroes", "엑스디너리 히어로즈", "엑디즈"],
  ["P1Harmony", "피원하모니"],
  ["CRAVITY", "크래비티"],
  ["DAY6", "데이식스"],

  // —— 솔로·밴드·기타
  ["IU", "아이유"],
  ["Psy", "싸이"],
  ["AKMU", "악동뮤지션", "악뮤"],
  ["BOL4", "볼빨간사춘기", "볼사"],
  ["Crush", "크러쉬"],
  ["ZICO", "지코"],
  ["Jay Park", "박재범"],
  ["TAEYEON", "태연"],
  ["G-DRAGON", "지드래곤", "GD"],
  ["JENNIE", "제니"],
  ["ROSÉ", "로제"],
  ["LISA", "리사"],
  ["JISOO", "지수"],
  ["Jung Kook", "Jungkook", "정국"],
  ["j-hope", "제이홉"],
  ["SUGA", "슈가", "Agust D"],
  ["RM", "알엠"],
  ["Jimin", "지민"],
  ["Jeon Somi", "전소미", "소미"],
  ["Sunmi", "선미"],
  ["CHUNG HA", "청하"],
  ["Hwasa", "화사"],
  ["HyunA", "현아"],
  ["BIBI", "비비"],
  ["Younha", "윤하"],
  ["Epik High", "에픽하이"],
  ["Dynamic Duo", "다이나믹듀오"],
  ["10CM", "십센치"],
  ["PAUL KIM", "폴킴"],
  ["Heize", "헤이즈"],
  ["SEULGI", "슬기"],
  ["WINTER", "윈터"],
  ["KARINA", "카리나"],
  ["GISELLE", "지젤"],
  ["NINGNING", "닝닝"],
];
