/** 아티스트 한글↔영문 별칭 데이터 (같은 배열 = 같은 아티스트) */


export const ARTIST_ALIAS_GROUPS: readonly (readonly string[])[] = [
  // —— 걸그룹
  ["fromis_9", "fromis9", "프로미스나인", "프로미스 나인"],
  ["aespa", "æspa", "에스파", "애스파"],
  ["BLACKPINK", "블랙핑크"],
  ["NewJeans", "뉴진스"],
  ["IVE", "아이브"],
  ["LE SSERAFIM", "LESSERAFIM", "르세라핌"],
  ["(G)I-DLE", "GIDLE", "아이들", "여자아이들"],
  ["TWICE", "트와이스"],
  ["Red Velvet", "레드벨벳"],
  ["ITZY", "있지"],
  ["NMIXX", "엔믹스"],
  ["ILLIT", "아일릿"],
  ["BABYMONSTER", "베이비몬스터"],
  ["TWS", "투어스"],
  ["MAMAMOO", "마마무"],
  ["Apink", "에이핑크"],
  ["Oh My Girl", "오마이걸"],
  ["WJSN", "우주소녀"],
  ["LOONA", "이달의 소녀"],
  ["Kep1er", "케플러"],
  ["STAYC", "스테이씨"],
  ["KISS OF LIFE", "키스오브라이프", "킾라"],
  ["tripleS", "트리플에스"],
  ["ARTMS", "아르테미스"],
  ["QWER", "큐더블유이알"],
  ["Girls' Generation", "소녀시대", "SNSD"],
  ["2NE1", "투애니원"],
  ["Wonder Girls", "원더걸스"],
  ["f(x)", "에프엑스"],

  // —— 보이그룹
  ["BTS", "방탄소년단", "방탄"],
  ["ZEROBASEONE", "ZB1", "제로베이스원"],
  ["RIIZE", "라이즈"],
  ["BOYNEXTDOOR", "보이넥스트도어"],
  ["ENHYPEN", "엔하이픈"],
  ["TOMORROW X TOGETHER", "TXT", "투모로우바이투게더"],
  ["Stray Kids", "스트레이키즈", "스키즈"],
  ["SEVENTEEN", "세븐틴"],
  ["ATEEZ", "에이티즈"],
  ["THE BOYZ", "더보이즈"],
  ["NCT", "엔시티"],
  ["NCT DREAM", "엔시티 드림", "엔시티드림"],
  ["NCT 127", "엔시티 127", "엔시티127"],
  ["NCT WISH", "엔시티 위시", "엔시티위시"],
  ["WayV", "웨이션브이"],
  ["EXO", "엑소"],
  ["SHINee", "샤이니"],
  ["BIGBANG", "빅뱅"],
  ["Super Junior", "슈퍼주니어"],
  ["TREASURE", "트레저"],
  ["iKON", "아이콘"],
  ["WINNER", "위너"],
  ["GOT7", "갓세븐"],
  ["MONSTA X", "몬스타엑스"],
  ["ASTRO", "아스트로"],
  ["SF9", "에스에프나인"],
  ["AB6IX", "에이비식스"],
  ["CIX", "씨아이엑스"],
  ["ONEUS", "원어스"],
  ["ONEWE", "원위"],
  ["PENTAGON", "펜타곤"],
  ["VICTON", "빅톤"],
  ["VERIVERY", "베리베리"],
  ["EPEX", "이펙스"],
  ["TEMPEST", "템페스트"],
  ["EVNNE", "이븐"],
  ["xikers", "싸이커스"],
  ["AMPERS&ONE", "앰퍼샌드원"],
  ["PLAVE", "플레이브"],
  ["xdinary Heroes", "엑스디너리 히어로즈", "엑디즈"],
  ["P1Harmony", "피원하모니"],
  ["CRAVITY", "크래비티"],
  ["DAY6", "데이식스"],

  // —— 솔로·밴드·기타
  ["IU", "아이유"],
  ["Psy", "싸이"],
  ["AKMU", "악동뮤지션", "악뮤"],
  ["BOL4", "볼빨간사춘기", "볼사"],
  ["Crush", "크러쉬"],
  ["ZICO", "지코"],
  ["Jay Park", "박재범"],
  ["TAEYEON", "태연"],
  ["G-DRAGON", "지드래곤", "GD"],
  ["JENNIE", "제니"],
  ["ROSÉ", "로제"],
  ["LISA", "리사"],
  ["JISOO", "지수"],
  ["Jung Kook", "Jungkook", "정국"],
  ["j-hope", "제이홉"],
  ["SUGA", "슈가", "Agust D"],
  ["RM", "알엠"],
  ["Jimin", "지민"],
  ["Jeon Somi", "전소미", "소미"],
  ["Sunmi", "선미"],
  ["CHUNG HA", "청하"],
  ["Hwasa", "화사"],
  ["HyunA", "현아"],
  ["BIBI", "비비"],
  ["Younha", "윤하"],
  ["Epik High", "에픽하이"],
  ["Dynamic Duo", "다이나믹듀오"],
  ["10CM", "십센치"],
  ["PAUL KIM", "폴킴"],
  ["Heize", "헤이즈"],
  ["SEULGI", "슬기"],
  ["WINTER", "윈터"],
  ["KARINA", "카리나"],
  ["GISELLE", "지젤"],
  ["NINGNING", "닝닝"],

  // —— 해외 팝
  ["Taylor Swift", "테일러 스위프트", "테일러스위프트"],
  ["Billie Eilish", "빌리 아일리시", "빌리아일리시"],
  ["Ariana Grande", "아리아나 그란데", "아리아나그란데"],
  ["Dua Lipa", "두아 리파", "두아리파"],
  ["The Weeknd", "위켄드", "더 위켄드"],
  ["Bruno Mars", "브루노 마스", "브루노마스"],
  ["Ed Sheeran", "에드 시런", "에드시런"],
  ["Harry Styles", "해리 스타일스", "해리스타일스"],
  ["Olivia Rodrigo", "올리비아 로드리고", "올리비아로드리고"],
  ["Sabrina Carpenter", "사브리나 카펜터", "사브리나카펜터"],
  ["Lana Del Rey", "라나 델 레이", "라나델레이"],
  ["Lady Gaga", "레이디 가가", "레이디가가"],
  ["Beyoncé", "Beyonce", "비욘세"],
  ["Rihanna", "리한나"],
  ["Adele", "아델"],
  ["Sia", "시아"],
  ["Charlie Puth", "찰리 푸스", "찰리푸스"],
  ["Justin Bieber", "저스틴 비버", "저스틴비버"],
  ["Shawn Mendes", "션 멘데스", "션멘데스"],
  ["Sam Smith", "샘 스미스", "샘스미스"],
  ["Doja Cat", "도자 캣", "도자캣"],
  ["SZA", "에스지에이"],
  ["Tyler, The Creator", "Tyler The Creator", "타일러 더 크리에이터"],
  ["Frank Ocean", "프랭크 오션", "프랭크오션"],
  ["The 1975", "더 1975"],
  ["Arctic Monkeys", "악틱 몽키즈", "악틱몽키즈"],
  ["Radiohead", "라디오헤드"],
  ["Coldplay", "콜드플레이"],
  ["Imagine Dragons", "이매진 드래곤스", "이매진드래곤스"],
  ["Maroon 5", "마룬파이브", "마룬 5"],
  ["OneRepublic", "원리퍼블릭"],
  ["Glass Animals", "글래스 애니멀스", "글래스애니멀스"],

  // —— 해외 힙합·R&B
  ["Mobb Deep", "맙 딥", "맙딥"],
  ["Nas", "나스"],
  ["Jay-Z", "Jay Z", "제이지"],
  ["Kanye West", "Ye", "카니예 웨스트", "카니예"],
  ["Kendrick Lamar", "켄드릭 라마", "켄드릭라마"],
  ["Drake", "드레이크"],
  ["J. Cole", "J Cole", "제이 콜", "제이콜"],
  ["Travis Scott", "트래비스 스콧", "트래비스스콧"],
  ["Eminem", "에미넴"],
  ["Notorious B.I.G.", "The Notorious B.I.G.", "노토리우스 비아이지", "빅기"],
  ["2Pac", "Tupac", "투팍"],
  ["Wu-Tang Clan", "우탱클랜", "우탱 클랜"],
  ["A Tribe Called Quest", "어 트라이브 콜드 퀘스트"],
  ["Outkast", "아웃캐스트"],
  ["Childish Gambino", "차일디시 감비노"],
  ["Mac Miller", "맥 밀러", "맥밀러"],
  ["Anderson .Paak", "Anderson Paak", "앤더슨 팩"],
  ["Daniel Caesar", "다니엘 시저", "다니엘시저"],
  ["Giveon", "기브온"],
  ["Brent Faiyaz", "브렌트 페이아즈"],
  ["Summer Walker", "섬머 워커", "섬머워커"],
  ["H.E.R.", "HER", "에이치이알"],
  ["JID", "제이드"],
  ["Denzel Curry", "덴젤 커리", "덴젤커리"],
  ["JPEGMAFIA", "JPEG Mafia", "제이펙마피아"],
  ["Playboi Carti", "플레이보이 카티"],
  ["Lil Uzi Vert", "릴 우지 버트"],
  ["Future", "퓨처"],
  ["Metro Boomin", "메트로 부민", "메트로부민"],
  ["Nicki Minaj", "니키 미나즈", "니키미나즈"],
  ["Cardi B", "카디 비", "카디비"],
  ["Megan Thee Stallion", "메간 더 스탤리온"],
  ["Ice Spice", "아이스 스파이스"],

  // —— 해외 록·얼터너티브·인디
  ["The Beatles", "비틀즈", "비틀스"],
  ["Queen", "퀸"],
  ["Pink Floyd", "핑크 플로이드", "핑크플로이드"],
  ["Led Zeppelin", "레드 제플린", "레드제플린"],
  ["Nirvana", "너바나"],
  ["Foo Fighters", "푸 파이터스", "푸파이터스"],
  ["Red Hot Chili Peppers", "레드 핫 칠리 페퍼스", "레드핫칠리페퍼스"],
  ["Linkin Park", "린킨 파크", "린킨파크"],
  ["Muse", "뮤즈"],
  ["Oasis", "오아시스"],
  ["Blur", "블러"],
  ["The Strokes", "더 스트로크스", "스트로크스"],
  ["Tame Impala", "테임 임팔라", "테임임팔라"],
  ["Mac DeMarco", "맥 드마르코", "맥드마르코"],
  ["Clairo", "클라이로"],
  ["Phoebe Bridgers", "피비 브리저스"],
  ["Boygenius", "보이지니어스"],
  ["Japanese Breakfast", "재패니즈 브렉퍼스트"],
  ["Beabadoobee", "비바두비"],
  ["The Smiths", "더 스미스", "스미스"],
  ["Joy Division", "조이 디비전", "조이디비전"],
  ["Depeche Mode", "디페쉬 모드", "디페쉬모드"],
  ["New Order", "뉴 오더", "뉴오더"],

  // —— 해외 일렉트로닉·기타
  ["Daft Punk", "다프트 펑크", "다프트펑크"],
  ["Calvin Harris", "캘빈 해리스", "캘빈해리스"],
  ["Avicii", "아비치"],
  ["Skrillex", "스크릴렉스"],
  ["Flume", "플룸"],
  ["Fred again..", "Fred again", "프레드 어게인"],
  ["Disclosure", "디스클로저"],
  ["ODESZA", "오데자"],
  ["Porter Robinson", "포터 로빈슨", "포터로빈슨"],
  ["Michael Jackson", "마이클 잭슨", "마이클잭슨"],
  ["Prince", "프린스"],
  ["David Bowie", "데이비드 보위", "데이비드보위"],
  ["Stevie Wonder", "스티비 원더", "스티비원더"],
  ["Whitney Houston", "휘트니 휴스턴", "휘트니휴스턴"],
  ["Madonna", "마돈나"],
  ["ABBA", "아바"],
  ["Fleetwood Mac", "플리트우드 맥", "플리트우드맥"],
  ["Norah Jones", "노라 존스", "노라존스"],
  ["Amy Winehouse", "에이미 와인하우스", "에이미와인하우스"],
  ["Alicia Keys", "알리샤 키스", "알리샤키스"],
  ["John Mayer", "존 메이어", "존메이어"],
];
